#!/bin/bash
# Script de carga automática del mundo RPG
# Generado para testing de producción

WORLD="mmorpg"
echo "=== Iniciando carga de mundo RPG para testing ==="
echo "Mundo: $WORLD"
echo ""

# Nota: Este script genera comandos que debes ejecutar en la consola del servidor
# o mediante RCON. Los comandos están comentados para que puedas copiarlos manualmente.

echo "# ========================================="
echo "# COMANDOS DE SPAWN DE NPCs"
echo "# ========================================="
echo ""
echo "# Maestro de Armas (Trainer)"
echo "rpg npc spawn npc_trainer_warrior $WORLD 10 64 10"
echo ""
echo "# Comerciante General (Merchant)"
echo "rpg npc spawn npc_merchant_general $WORLD -10 64 10"
echo ""
echo "# Alcalde del Pueblo (Quest Giver)"
echo "rpg npc spawn npc_questgiver_start $WORLD 0 64 20"
echo ""
echo "# Herrero Legendario (Weapon Merchant)"
echo "rpg npc spawn npc_blacksmith $WORLD 20 64 -10"
echo ""

echo "# ========================================="
echo "# COMANDOS DE SPAWN DE MOBS"
echo "# ========================================="
echo ""
echo "# Zombie Warrior (nivel 5)"
echo "rpg mob spawn zombie_warrior $WORLD 150 64 0"
echo ""
echo "# Skeleton Archer (nivel 7)"
echo "rpg mob spawn skeleton_archer $WORLD 200 64 50"
echo ""
echo "# Spider Hunter (nivel 10)"
echo "rpg mob spawn spider_hunter $WORLD 250 64 -50"
echo ""
echo "# Boss Dragon (nivel 50 - respawn cada hora)"
echo "rpg mob spawn boss_dragon $WORLD -350 68 -350"
echo ""

echo "# ========================================="
echo "# CONFIGURACIÓN DE ZONAS DE RESPAWN"
echo "# ========================================="
echo ""
echo "# Zona Segura (Ciudad)"
echo "rpg zone create safe_zone SAFE $WORLD -50 60 -50 50 100 50"
echo ""
echo "# Zona de Farmeo (Campo de Entrenamiento)"
echo "rpg zone create farming_zone FARMEO $WORLD 100 60 -100 300 80 100"
echo "rpg zone setmobs farming_zone 20 30"
echo ""
echo "# Zona de Dungeon (Cripta Oscura)"
echo "rpg zone create dungeon_entrance DUNGEON $WORLD -200 50 100 -100 70 200"
echo "rpg zone setmobs dungeon_entrance 30 15"
echo "rpg zone setboss dungeon_entrance -150 55 150"
echo ""
echo "# Arena de Boss (Coliseo del Dragón)"
echo "rpg zone create boss_arena BOSS_ARENA $WORLD -400 65 -400 -300 75 -300"
echo "rpg zone setboss boss_arena -350 68 -350"
echo ""

echo "# ========================================="
echo "# WAYPOINTS DE TELETRANSPORTE"
echo "# ========================================="
echo ""
echo "# Plaza Central (nivel 1)"
echo "rpg waypoint create waypoint_spawn \"Plaza Central\" $WORLD 0 64 0 1"
echo ""
echo "# Campo de Entrenamiento (nivel 5)"
echo "rpg waypoint create waypoint_farming \"Campo de Entrenamiento\" $WORLD 200 64 0 5"
echo ""
echo "# Cripta Oscura (nivel 10)"
echo "rpg waypoint create waypoint_dungeon \"Cripta Oscura\" $WORLD -150 64 150 10"
echo ""
echo "# Coliseo (nivel 30)"
echo "rpg waypoint create waypoint_boss \"Coliseo\" $WORLD -350 68 -350 30"
echo ""

echo "=== Comandos generados. Copia y ejecuta en la consola del servidor ==="
echo ""
echo "NOTA: Puedes acceder al editor visual en:"
echo "http://localhost:5000/rpg-layout"
echo ""
echo "Para ejecutar todos estos comandos automáticamente vía RCON:"
echo "1. Configura las variables RCON_HOST, RCON_PORT, RCON_PASSWORD"
echo "2. Ejecuta: bash spawn_rpg_world_auto.sh"
